create extension if not exists pgcrypto;

create table if not exists public.profiles (
    id uuid primary key references auth.users(id) on delete cascade,
    first_name text not null,
    last_name text not null,
    phone text,
    created_at timestamptz not null default now()
);

create table if not exists public.rooms (
    id bigint generated by default as identity primary key,
    name text not null,
    slug text unique not null,
    description text not null,
    price numeric(10,2) not null check (price >= 0),
    max_guests integer not null check (max_guests > 0),
    beds text not null,
    size text not null,
    view text not null,
    image_url text,
    amenities text[] not null default '{}',
    available boolean not null default true,
    created_at timestamptz not null default now()
);

create table if not exists public.reservations (
    id uuid primary key default gen_random_uuid(),
    user_id uuid not null references auth.users(id) on delete cascade,
    room_id bigint not null references public.rooms(id),
    first_name text not null,
    last_name text not null,
    email text not null,
    phone text not null,
    check_in date not null,
    check_out date not null,
    adults integer not null default 1 check (adults > 0),
    children integer not null default 0 check (children >= 0),
    special_requests text,
    nights integer generated always as ((check_out - check_in)) stored,
    total numeric(10,2) not null check (total >= 0),
    status text not null default 'Pending' check (status in ('Pending','Confirmed','Cancelled')),
    created_at timestamptz not null default now(),
    constraint valid_dates check (check_out > check_in)
);

alter table public.profiles enable row level security;
alter table public.rooms enable row level security;
alter table public.reservations enable row level security;

drop policy if exists "Public can view available rooms" on public.rooms;
create policy "Public can view available rooms"
on public.rooms for select
using (available = true);

drop policy if exists "Users can view own profile" on public.profiles;
create policy "Users can view own profile"
on public.profiles for select
to authenticated
using (auth.uid() = id);

drop policy if exists "Users can update own profile" on public.profiles;
create policy "Users can update own profile"
on public.profiles for update
to authenticated
using (auth.uid() = id)
with check (auth.uid() = id);

drop policy if exists "Users can view own reservations" on public.reservations;
create policy "Users can view own reservations"
on public.reservations for select
to authenticated
using (auth.uid() = user_id);

drop policy if exists "Users can create own reservations" on public.reservations;
create policy "Users can create own reservations"
on public.reservations for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "Users can cancel own reservations" on public.reservations;
create policy "Users can cancel own reservations"
on public.reservations for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
    insert into public.profiles (id, first_name, last_name, phone)
    values (
        new.id,
        coalesce(new.raw_user_meta_data->>'first_name', ''),
        coalesce(new.raw_user_meta_data->>'last_name', ''),
        coalesce(new.raw_user_meta_data->>'phone', '')
    )
    on conflict (id) do update set
        first_name = excluded.first_name,
        last_name = excluded.last_name,
        phone = excluded.phone;
    return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();

insert into public.rooms
(name, slug, description, price, max_guests, beds, size, view, image_url, amenities, available)
values
(
    'Deluxe Garden Room',
    'deluxe-garden',
    'A comfortable room surrounded by relaxing garden views.',
    3500,
    2,
    '1 King Bed',
    '32 sqm',
    'Garden View',
    'https://images.unsplash.com/photo-1566665797739-1674de7a421a?auto=format&fit=crop&w=1200&q=80',
    array['Free Wi-Fi','Air Conditioning','Smart TV','Mini Refrigerator'],
    true
),
(
    'Premium Pool View',
    'premium-pool',
    'A stylish room with a peaceful view of the resort pool.',
    4500,
    3,
    '1 King Bed + 1 Single Bed',
    '38 sqm',
    'Pool View',
    'https://images.unsplash.com/photo-1590490360182-c33d57733427?auto=format&fit=crop&w=1200&q=80',
    array['Free Wi-Fi','Air Conditioning','Smart TV','Breakfast Included'],
    true
),
(
    'Family Suite',
    'family-suite',
    'A spacious suite designed for families and small groups.',
    6000,
    5,
    '2 Queen Beds',
    '55 sqm',
    'Garden View',
    'https://images.unsplash.com/photo-1595576508898-0ad5c879a061?auto=format&fit=crop&w=1200&q=80',
    array['Free Wi-Fi','Air Conditioning','Kitchenette','Breakfast Included'],
    true
),
(
    'Executive Suite',
    'executive-suite',
    'An elegant suite offering extra space and premium comfort.',
    7500,
    4,
    '1 King Bed + Sofa Bed',
    '62 sqm',
    'Pool View',
    'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=1200&q=80',
    array['Free Wi-Fi','Air Conditioning','Living Area','Breakfast Included'],
    true
),
(
    'Honeymoon Villa',
    'honeymoon-villa',
    'A private villa made for a quiet and memorable stay.',
    9000,
    2,
    '1 King Bed',
    '70 sqm',
    'Private Garden',
    'https://images.unsplash.com/photo-1601918774946-25832a4be0d6?auto=format&fit=crop&w=1200&q=80',
    array['Free Wi-Fi','Private Patio','Bathtub','Breakfast Included'],
    true
),
(
    'Presidential Villa',
    'presidential-villa',
    'Our largest accommodation with premium resort amenities.',
    12000,
    6,
    '2 King Beds',
    '95 sqm',
    'Resort View',
    'https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=1200&q=80',
    array['Free Wi-Fi','Private Pool','Living Room','Breakfast Included'],
    true
)
on conflict (slug) do update set
    name = excluded.name,
    description = excluded.description,
    price = excluded.price,
    max_guests = excluded.max_guests,
    beds = excluded.beds,
    size = excluded.size,
    view = excluded.view,
    image_url = excluded.image_url,
    amenities = excluded.amenities,
    available = excluded.available;
